### ISSUE TITLE
No habit tracker graph rendered

### ISSUE THREAD

**Issue by jdeluyck** [hkgnp/logseq-trackhabits2-plugin#8] opened 2024-04-13 19:00 UTC
Hi, I've been trying out the habit tracker, but it no longer seems to work?
Using logseq 0.10.8.

I've added two test-items
![image](https://github.com/hkgnp/logseq-trackhabits2-plugin/assets/5451787/7c1d0bf3-70c5-4a0f-9cce-176a2b4459a1)

Then executed /track habits, I see that it's added a macro, but nothing actually comes out.
![image](https://github.com/hkgnp/logseq-trackhabits2-plugin/assets/5451787/9e32fe7a-f469-4ff6-abf6-e8b38aafcca0)

**Comment by benjypng** [comment] 2024-04-15 08:27
Apologies 🙏 Please try the latest version.

**Comment by jdeluyck** [comment] 2024-04-15 16:18
Thank you! Works now... though I'm seeing other odd behaviour

**Comment by jdeluyck** [comment] 2024-04-15 16:24
When all (up to today) are marked done, i get

![image](https://github.com/hkgnp/logseq-trackhabits2-plugin/assets/5451787/c4fd1d19-6dcd-487f-a6cb-e6029f541ccf)

When I unmark eg today, I get
![image](https://github.com/hkgnp/logseq-trackhabits2-plugin/assets/5451787/9754c51f-0bc8-4e09-867c-e7a960a9f001)


but nothing for the 12th.

![image](https://github.com/hkgnp/logseq-trackhabits2-plugin/assets/5451787/85d112ac-b8c9-492d-bcb5-7f886ed33cf3)

**Comment by benjypng** [comment] 2024-04-17 09:05
Apologies, please try the latest version.

**Comment by jdeluyck** [comment] 2024-04-17 16:45
Hi,

Better again :)

Still one issue: items are being shown multiple times for the same date?

![image](https://github.com/hkgnp/logseq-trackhabits2-plugin/assets/5451787/84a1ff6c-1abc-4b1b-aa25-a43792f269f8)

As you can see, 15/04 is listed twice - and if you add more items you get more rows per date.

Thank you for working on this!

**Comment by benjypng** [comment] 2024-04-18 08:42
Hi, apologies forgot to redo the habits array. Please try again.

**Comment by jdeluyck** [comment] 2024-04-18 18:02
Thank you again!

For me this works now fine, but my girlfriend sees some really weird behaviour I can't explain.

She's added several habits now over several days, but somehow the plugin only shows two days
![Screenshot_20240418_195825](https://github.com/hkgnp/logseq-trackhabits2-plugin/assets/5451787/eeb10179-1132-436b-a409-d1e99ca912a1)
![Screenshot_20240418_200010](https://github.com/hkgnp/logseq-trackhabits2-plugin/assets/5451787/89ada146-3d50-4951-b31b-8bf4d3ac1b6f)

There are even more days in the #habit-tracker page but they didn't fit in the screenshot.

Is there any debug info I can get you?

**Comment by benjypng** [comment] 2024-04-19 01:31
Did she customise the maximum number of entries the plugin should return (in the settings page)?

**Comment by jdeluyck** [comment] 2024-04-19 17:23
> Did she customise the maximum number of entries the plugin should return (in the settings page)?

No. It's set to 10, as it is on my installation.

**Comment by benjypng** [comment] 2024-04-22 14:03
Hmm, I cannot seem to reproduce it though. The only idea I have is that maybe the graph needs to be indexed but I am not sure if she wants to do that.

Am going to close this issue since the original one has been resolved. Feel free to open a new one for this new issue if you like.

**Closed as completed by benjypng** 2024-04-22 14:03 UTC
Labels: bug
